version: '3.8'

services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb_prod
    ports:
      - "18080:8080"
    volumes:
      - ./data:/usr/app/data
    env_file:
      - .env
    restart: unless-stopped

